name: Create Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Package extension
        uses: thedoctor0/zip-release@master
        with:
          directory: dist/
          filename: 'yt-dm-${{ github.ref_name }}.zip'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/yt-dm-${{ github.ref_name }}.zip'
          name: 'Release ${{ github.ref_name }}'
          generate_release_notes: true 