name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Prepare packaged directory
        run: |
          PACKAGE_DIR=yt-dm-${{ github.ref_name }}
          mkdir -p "$PACKAGE_DIR"
          cp -r dist/* "$PACKAGE_DIR"/

      - name: Package extension
        run: |
          zip -r yt-dm-${{ github.ref_name }}.zip \
            yt-dm-${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            yt-dm-${{ github.ref_name }}.zip
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
